TWITTER_KEY: 'TEi7l5YEPPxu9vdzcXNv5w'
TWITTER_SECRET: 'RomyChJKYCfsGfJD6jlqaqL777rzAOFsM7OBzSSC9hk'
# OAUTH_KEY: '287456668-wju6YUa3wCKXmeS8b9hOsSxYm35suQi2d3f4aItj'
# OAUTH_SECRET: 'MZMebRq9sAl7cIlTUOkmxWIo2puORlvuK2r1FzpFpM'